site_name: Leo's Blog
site_url: https://leostrange05.github.io/

nav:
  - üè† Home: index.md
  - Branch one:
    - home: Tab1/index.md
    - page: Tab1/page-1.md
    - another page:
      - subpage: Tab1/new/page-3.md
  - Branch two:
    - Page1: TAB2/page-1.md
  
  - ÂÖ≥‰∫éÊú¨Á´ô: diary.md

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: ÂàáÊç¢Ëá≥Ê∑±Ëâ≤Ê®°Âºè
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: lime
      toggle:
        icon: material/brightness-3
        name: ÂàáÊç¢Ëá≥ÊµÖËâ≤Ê®°Âºè

  font:
    text: Ubuntu
    code: Jetbrains Mono
  language: zh
  icon:
    logo: material/clippy
    annotation: material/arrow-right-circle-outline
    
  favicon: 
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.annotate

plugins:
  - search
  - macros:
      module_name: main  # This points to your main.py
      
markdown_extensions:  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
                     
  - attr_list         # annotation
  - md_in_html
  - pymdownx.superfences

  - attr_list         # button

  - pymdownx.highlight: # code block
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.superfences # content tab
  - pymdownx.tabbed:
      alternate_style: true

  - tables            # table

  - attr_list         # icon emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - attr_list          # image
  - md_in_html
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leostrange05
      name: GitHub
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/32313515/leostrange
      name: Stack Overflow
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0009-0003-4712-4764)
      name: ORCID